# Generated by Django 3.0.5 on 2020-08-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_model_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='model_feedback_name',
        ),
    ]
