# Generated by Django 3.0.5 on 2020-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_feedback_model_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='model_feedback_name',
            field=models.CharField(default='Name not provided', max_length=30),
        ),
    ]
