# Generated by Django 3.0.5 on 2020-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback_model_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='model_feedback_age',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='model_feedback_email',
            field=models.CharField(default='Email not provided', max_length=40),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='model_feedback_text',
            field=models.CharField(max_length=200),
        ),
    ]
