# Generated by Django 3.0.5 on 2020-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200907_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='model_feedback_age',
            field=models.IntegerField(default=1),
        ),
    ]
